
-- tested in derby

DROP TABLE JOBS_EXE;
DROP TABLE JOBS_HIS;
DROP TABLE JOBS_ISU;
DROP TABLE JOBS_PLN;
DROP TABLE JOBS_CFG;

CREATE TABLE JOBS_EXE (
	J_BAT INT NOT NULL,
	J_UID VARCHAR(50) NOT NULL,
	J_CLS VARCHAR(100) NOT NULL,
	J_PAR VARCHAR(100) NULL,
	J_STA INT NOT NULL,
	J_TIMREG VARCHAR(23) NOT NULL,
	J_TIMPLN BIGINT NULL,
	J_SID VARCHAR(30) NULL,
	J_TIMEXE VARCHAR(23) NULL,
	J_TIMEND VARCHAR(23) NULL,
	J_TIM INT NULL,
	J_RMK VARCHAR(100) NULL,
	J_LOG VARCHAR(100) NULL,
	J_ERR VARCHAR(1000) NULL,
	PRIMARY KEY (J_BAT, J_UID)
);

-- JOBS_HIS same as JOBS_EXE

CREATE TABLE JOBS_ISU (
	J_BAT INT NOT NULL,
	J_UID VARCHAR(50) NOT NULL,
	PRIMARY KEY (J_BAT, J_UID)
);

CREATE TABLE JOBS_PLN (
	J_BAT INT NOT NULL,
	J_UID VARCHAR(50) NOT NULL,
	J_TIMPLN BIGINT NOT NULL,
	J_SID VARCHAR(30) NULL,
	PRIMARY KEY (J_BAT, J_UID)
);
create index IDX_PLN on JOBS_PLN (J_TIMPLN);
create index IDX_SID on JOBS_PLN (J_SID);

CREATE TABLE JOBS_CFG (
	J_KEY VARCHAR(30) NOT NULL,
	J_VAL VARCHAR(50) NOT NULL,
	PRIMARY KEY (J_KEY)
);

